** Лабораторная работа №4 “Нейронные сети”**

Долматович Алина, 858641

Набор данных ex4data1.mat (такой же, как в лабораторной работе №2) представляет собой файл формата *.mat (т.е. сохраненного из Matlab). Набор содержит 5000 изображений 20x20 в оттенках серого. Каждый пиксель представляет собой значение яркости (вещественное число). Каждое изображение сохранено в виде вектора из 400 элементов. В результате загрузки набора данных должна быть получена матрица 5000x400. Далее расположены метки классов изображений от 1 до 9 (соответствуют цифрам от 1 до 9), а также 10 (соответствует цифре 0).

In [1]:
import pandas
from scipy.io import loadmat
import numpy as np
import random
import scipy.optimize as optimize
import matplotlib.pyplot as pyplot

Загрузите данные ex4data1.mat из файла.

In [2]:
data = loadmat('ex4data1.mat')
y = data["y"]
x = data["X"]
print(x.shape)
print(y)

(5000, 400)
[[10]
 [10]
 [10]
 ...
 [ 9]
 [ 9]
 [ 9]]


Загрузите веса нейронной сети из файла ex4weights.mat, который содержит две матрицы Θ(1) (25, 401) и Θ(2) (10, 26). 
Какова структура полученной нейронной сети?

In [3]:
weightsData = loadmat('ex4weights.mat')
theta1 = weightsData["Theta1"]
theta2 = weightsData["Theta2"]
print(theta1)
print(theta2)


[[-2.25623899e-02 -1.05624163e-08  2.19414684e-09 ... -1.30529929e-05
  -5.04175101e-06  2.80464449e-09]
 [-9.83811294e-02  7.66168682e-09 -9.75873689e-09 ... -5.60134007e-05
   2.00940969e-07  3.54422854e-09]
 [ 1.16156052e-01 -8.77654466e-09  8.16037764e-09 ... -1.20951657e-04
  -2.33669661e-06 -7.50668099e-09]
 ...
 [-1.83220638e-01 -8.89272060e-09 -9.81968100e-09 ...  2.35311186e-05
  -3.25484493e-06  9.02499060e-09]
 [-7.02096331e-01  3.05178374e-10  2.56061008e-09 ... -8.61759744e-04
   9.43449909e-05  3.83761998e-09]
 [-3.50933229e-01  8.85876862e-09 -6.57515140e-10 ... -1.80365926e-06
  -8.14464807e-06  8.79454531e-09]]
[[-0.76100352 -1.21244498 -0.10187131 -2.36850085 -1.05778129 -2.20823629
   0.56383834  1.21105294  2.21030997  0.44456156 -1.18244872  1.04289112
  -1.60558756  1.30419943  1.37175046  1.74825095 -0.23365648 -1.52014483
   1.15324176  0.10368082 -0.37207719 -0.61530019 -0.1256836  -2.27193038
  -0.71836208 -1.29690315]
 [-0.61785176  0.61559207 -1.26550639  1.

Реализуйте функцию прямого распространения с сигмоидом в качестве функции активации. 




In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def getSigmoidData(ones, x, theta):
    if x.shape[1] != theta.shape[1]:
        x = np.hstack((ones, x))
    z = np.dot(x, theta.T)
    return sigmoid(z)

def h(theta1, theta2, x):
    m = len(x)
    ones = np.ones((m, 1))
    x = getSigmoidData(ones, x, theta1)
    return x, getSigmoidData(ones, x, theta2)

l1, l2 = h(theta1, theta2, x)
print(l1, l2)

(array([[5.03618685e-02, 7.93957162e-02, 9.93001966e-01, ...,
        9.72517962e-01, 9.43421623e-01, 1.07213787e-01],
       [8.05782163e-03, 5.10486829e-02, 9.33671593e-01, ...,
        8.91385592e-01, 9.90982126e-01, 5.94701645e-02],
       [1.41949887e-02, 2.44354705e-02, 9.97518887e-01, ...,
        8.24334311e-01, 9.56466386e-01, 8.86760824e-02],
       ...,
       [2.96781175e-01, 7.32901746e-01, 1.57724076e-01, ...,
        8.60396828e-01, 3.98474223e-02, 1.51177198e-01],
       [8.51205095e-01, 3.58434539e-01, 1.83675450e-01, ...,
        9.84854863e-01, 2.75399966e-01, 4.35605471e-02],
       [9.72262381e-01, 5.48598771e-06, 9.93379633e-01, ...,
        9.99235749e-01, 8.96120297e-01, 5.00966928e-02]]), array([[1.12661530e-04, 1.74127856e-03, 2.52696959e-03, ...,
        4.01468105e-04, 6.48072305e-03, 9.95734012e-01],
       [4.79026796e-04, 2.41495958e-03, 3.44755685e-03, ...,
        2.39107046e-03, 1.97025086e-03, 9.95696931e-01],
       [8.85702310e-05, 3.24266731e-03, 2

Вычислите процент правильных классификаций на обучающей выборке. 
Сравните полученный результат с логистической регрессией.




In [5]:
def predictionPercentValue(resultLayer, y):
    predictions = np.argmax(resultLayer, axis=1) + 1
    predictionsCount = 0
    for predictionValue, realValue in zip(predictions, y):
        if predictionValue == realValue:
            predictionsCount += 1
    percentValue =  float(predictionsCount) / len(y) * 100
    return percentValue

predictionPercentValue(l2, y)

97.52

Перекодируйте исходные метки классов по схеме one-hot.

In [6]:
oneHot = pandas.get_dummies(y.squeeze())
print(oneHot)

      1   2   3   4   5   6   7   8   9   10
0      0   0   0   0   0   0   0   0   0   1
1      0   0   0   0   0   0   0   0   0   1
2      0   0   0   0   0   0   0   0   0   1
3      0   0   0   0   0   0   0   0   0   1
4      0   0   0   0   0   0   0   0   0   1
5      0   0   0   0   0   0   0   0   0   1
6      0   0   0   0   0   0   0   0   0   1
7      0   0   0   0   0   0   0   0   0   1
8      0   0   0   0   0   0   0   0   0   1
9      0   0   0   0   0   0   0   0   0   1
10     0   0   0   0   0   0   0   0   0   1
11     0   0   0   0   0   0   0   0   0   1
12     0   0   0   0   0   0   0   0   0   1
13     0   0   0   0   0   0   0   0   0   1
14     0   0   0   0   0   0   0   0   0   1
15     0   0   0   0   0   0   0   0   0   1
16     0   0   0   0   0   0   0   0   0   1
17     0   0   0   0   0   0   0   0   0   1
18     0   0   0   0   0   0   0   0   0   1
19     0   0   0   0   0   0   0   0   0   1
20     0   0   0   0   0   0   0   0   0   1
21     0  

Реализуйте функцию стоимости для данной нейронной сети.



In [7]:
def costFunction(h, y, sumParameter=False):
    costs = []
    for hI, yI in zip(h, y):
        cost = sum((hI - yI) ** 2)
        costs.append(cost)
    return sum(costs) if sumParameter == True else np.array(costs)

oneHot = np.array(oneHot)
cost = costFunction(l2, oneHot, sumParameter=True)
print(cost)

304.66188263037867


Добавьте L2-регуляризацию в функцию стоимости.




In [8]:
def costFunctionL2(theta1, theta2, y, lmbda):
    l1, l2 = h(theta1, theta2, x)
    return sum(sum((l2 - y) ** 2) * lmbda / (2*len(y)))

lmbda = 10000
cost = costFunctionL2(theta1, theta2, oneHot, lmbda)
print(cost)

304.6618826303791


Реализуйте функцию вычисления производной для функции активации.



In [9]:
def sigmoidDerivate(x):
    return np.exp(-x) / ((1 + np.exp(-x)) ** 2)


Инициализируйте веса небольшими случайными числами.




In [10]:
def generateWeights(shape):
    weights = []
    for i in range(shape[0]):
        line = []
        for j in range(shape[1]):
            value = random.random()
            line.append(value)
        weights.append(line)
    return np.array(weights)


shape1 = (25, 401)
weights1 = generateWeights(shape1)
shape2 = (10, 26)
weights2 = generateWeights(shape2)
print(weights1)
print(weights2)

[[0.55834049 0.13843724 0.46427383 ... 0.54724108 0.91459109 0.57021491]
 [0.37937421 0.38585304 0.24026023 ... 0.57060667 0.78906209 0.64656655]
 [0.73315654 0.7799666  0.24944323 ... 0.80294996 0.38221454 0.25260087]
 ...
 [0.14346225 0.77850668 0.17422577 ... 0.69874132 0.65814727 0.56713698]
 [0.99885084 0.65487151 0.62371713 ... 0.79249464 0.72403238 0.09215733]
 [0.14931405 0.88429488 0.98346084 ... 0.76653804 0.54994841 0.7445928 ]]
[[0.39784257 0.23411826 0.46563697 0.68003213 0.87208086 0.22300989
  0.89971628 0.3946644  0.08255601 0.76861051 0.70336466 0.57545801
  0.39079081 0.21024054 0.86667021 0.68478767 0.98085624 0.85556835
  0.66557763 0.78332819 0.84026747 0.48566307 0.2408858  0.17204807
  0.7399757  0.40259441]
 [0.96626687 0.41140245 0.44166019 0.61269898 0.20223109 0.27300145
  0.99076932 0.16048062 0.45819706 0.36040194 0.17237104 0.26671334
  0.56387174 0.48424088 0.84752791 0.42959915 0.92327662 0.8808601
  0.43731663 0.64567834 0.57639302 0.15024366 0.32108664

Реализуйте алгоритм обратного распространения ошибки для данной конфигурации сети.



In [11]:
for j in xrange(100):
    l0 = x
    l1, l2 = h(weights1, weights2, l0)
    l2error = y - l2
    if (j% 100) == 0:
        print "Error:" + str(np.mean(np.abs(l2error)))
    l2delta = l2error*sigmoidDerivate(l2)
    l1error = l2delta.dot(weights2)
    l1delta = l1error * sigmoidDerivate(l1)
    weights1 += np.dot(l0.T, l1delta).T
    weights2 += np.dot(l1.T, l2delta).T


Error:4.500003929825936


ValueError: operands could not be broadcast together with shapes (5000,26) (5000,25) 

Для того, чтобы удостоверится в правильности вычисленных значений градиентов используйте метод проверки градиента 
с параметром ε = 10-4.



In [12]:
def gradient(weights, x, lmbda=0, alpha=10e-4):
    weights1, weights2 = weights[0], weights[1]
    for j in xrange(100):
        layer1 = sigmoid(np.dot(x, weights1.T)) 
        layer2 = sigmoid(np.dot(layer1, weights2.T)) 
        layer2delta = (layer2 - y) * (layer2 * (1-layer2))
        layer1delta = np.dot(layer2delta, weights2) * (layer1 * (1-layer1)) 
        l2Parameter = 1 - lmbda/len(x)
        weights2 = weights2 * l2Parameter - alpha * np.dot(layer1.T, layer2delta).T 
        weights1 = weights1 * l2Parameter - alpha * np.dot(x.T, layer1delta).T 
    return np.array([weights1, weights2])

gradient([weights1, weights2], x)

ValueError: shapes (5000,400) and (401,25) not aligned: 400 (dim 1) != 401 (dim 0)

Добавьте L2-регуляризацию в процесс вычисления градиентов.



In [ ]:
weights = gradient([weights1, weights2], x, 1)
weights1, weights2 = weights[0], weights[1]

Проверьте полученные значения градиента.



In [ ]:
l1, l2 = h(weights1, weights2, x)
print(l1.shape, l2.shape, x.shape)

Обучите нейронную сеть с использованием градиентного спуска или других более эффективных методов оптимизации.




In [ ]:
y = data["y"]
x = data["X"]
trainWeights1 = generateWeights((25, 401))
trainWeights2 = generateWeights((10, 26))
trainWeights = gradient([trainWeights1, trainWeights2], x, 0.0000001)
trainWeights1, trainWeights2 = trainWeights[0], trainWeights[1]
l1, l2 = h(trainWeights1, trainWeights2, x)

Вычислите процент правильных классификаций на обучающей выборке.

In [ ]:
predictionPercentValue(l2, y)

Визуализируйте скрытый слой обученной сети.



In [ ]:
def plotL1(l1):
    count = 25
    _, axis = pyplot.subplots(1, count)

    for j in range(count):
        matrix = l1.T[j].reshape(50, 100, order="F")
        axis[j].imshow(matrix)
        axis[j].axis("off")

    pyplot.show()
    
plotL1(l1)


Подберите параметр регуляризации. Как меняются изображения на скрытом слое в зависимости от данного параметра?



In [ ]:
lmbdas = [100000000, 1000, 0, 0.00001]

for lmbda in lmbdas:
    trainWeights = gradient([trainWeights1, trainWeights2], x, lmbda)
    trainWeights1, trainWeights2 = trainWeights[0], trainWeights[1]
    l1, l2 = h(trainWeights1, trainWeights2, x)
    print(lmbda)
    plotL1(l1)


**Вывод**

Нейронные сети используются для решения сложных задач, которые требуют аналитических вычислений подобных тем, что делает человеческий мозг. Самыми распространенными применениями нейронных сетей является:
- Классификация
- Предсказание
- Распознавание
Нейрон — это вычислительная единица, которая получает информацию, производит над ней простые вычисления и передает ее дальше. Они делятся на три основных типа: входной, скрытый и выходной. Также есть нейрон смещения и контекстный нейрон о которых мы поговорим в следующей статье. В том случае, когда нейросеть состоит из большого количества нейронов, вводят термин слоя. Соответственно, есть входной слой, который получает информацию, n скрытых слоев, которые ее обрабатывают и выходной слой, который выводит результат. У каждого из нейронов есть 2 основных параметра: входные данные (input data) и выходные данные (output data). В случае входного нейрона: input=output. В остальных, в поле input попадает суммарная информация всех нейронов с предыдущего слоя, после чего, она нормализуется, с помощью функции активации (пока что просто представим ее f(x)) и попадает в поле output.